### ISSUE TITLE
SBT-based project can't resolve 'json-schema-codegen-sbt' dependency

### ISSUE THREAD

**Issue by sixman9** [VoxSupplyChain/json-schema-codegen#1]
Hi,
As the default (unspecified) SBT resolvers don't appear to resolve your artifact in my project, is it at all possible that a, correctly configured, 'Resolver.bintrayRepo("owner", "repo")' declaration necessary/might work (See '[SBT-Resolvers][bintray-resolver]')? Something like the folowing (doesn't work :-( ):

    resolvers += Resolver.bintrayRepo("voxsupplychain" "ivy-public")

I followed your 2 concise SBT-build additions from the README but, when I try to run my new project (even simply invoking the 'sbt' console command (SBT 0.13.9) within my project's root directory), the project is unable to resolve your artifact(s) at one of its known repos (I list SBT repo URL output, below).

Just for the record, could you confirm that the following URL is where you'd expect to resolve version 0.3.0 of the 'json-schema-codegen-sbt' code dependency?

    http://dl.bintray.com/voxsupplychain/ivy-public/com.voxsupplychain/json-schema-codegen-sbt/scala_2.10/sbt_0.13/0.3.0

After adding only your code's dependency requirements to my project (it's a fresh Intellij IDEA SBT project), the sbt console is attempting to resolve to the following URLs:

\<SBT CLi output fragment\>
[warn] 	module not found: com.voxsupplychain#json-schema-codegen-sbt;0.3.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   **https://repo.typesafe.com/typesafe/ivy-releases/com.voxsupplychain/json-schema-codegen-sbt/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml**
[warn] ==== sbt-plugin-releases: tried
[warn]   **https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.voxsupplychain/json-schema-codegen-sbt/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml**
[warn] ==== local: tried
[warn]   **/Users/myLocalUserHome/.ivy2/local/com.voxsupplychain/json-schema-codegen-sbt/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml**
[warn] ==== jcenter: tried
[warn]   **https://jcenter.bintray.com/com/voxsupplychain/json-schema-codegen-sbt_2.10_0.13/0.3.0/json-schema-codegen-sbt-0.3.0.pom**
[warn] ==== public: tried
[warn]   **https://repo1.maven.org/maven2/com/voxsupplychain/json-schema-codegen-sbt_2.10_0.13/0.3.0/json-schema-codegen-sbt-0.3.0.pom**
[warn] ==== bintray-voxsupplychain-ivy-public: tried
[warn]   **https://dl.bintray.com/voxsupplychain/ivy-public/com/voxsupplychain/json-schema-codegen-sbt_2.10_0.13/0.3.0/json-schema-codegen-sbt-0.3.0.pom**
\</SBT CLi output fragment\>

Only the last URL is similar to the one I believe we're expecting (i.e. beginning with "https://dl.bintray.com...").

Could you have a look into this and give me a little advice, it would be great to make use of your library.

Thanks

Rich

[bintray-resolver]: http://www.scala-sbt.org/0.13/docs/Resolvers.html

**Comment by tptodorov** [comment]
Rich,

I have the following in my plugins.sbt:

resolvers ++= Seq(
  Resolver.url("vox-public-ivy", url("http://dl.bintray.com/content/voxsupplychain/ivy-public"))(Resolver.ivyStylePatterns)
)

addSbtPlugin("com.voxsupplychain" %% "json-schema-codegen-sbt" % "0.3.0")

and it resolves. It seems plugin resolvers are different than normal ones.

Todor
